modelDir: "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/model_checkpoints"
modelName: "newloss_terms1-2_tanh50_2021-10-13_18-48-14"
modelConfig: "/nfs/dust/cms/user/sobhatta/work/TopTagPol/Training/training_results/condor_jobs/newloss_terms1-2_tanh50_2021-10-13_18-48-14/test_config_largedataset.yml"
modelFiles:
    epoch10: "weights_10.hdf5"
    epoch14: "weights_14.hdf5"
classifiers:
    0vs1: "{node0}/({node0}+{node1})"
    0vs2: "{node0}/({node0}+{node2})"
samples:
    #- "sourceFiles/ZprimeToTT_M1000_W10_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-01.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M1000_W100_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-08.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M1000_W300_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-13.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M1250_W12p5_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-18.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M1250_W125_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-26.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M1250_W375_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-31.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M1500_W15_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-36.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M1500_W150_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-40.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M1500_W450_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-46.txt:treeMaker/tree"
    - "sourceFiles/ZprimeToTT_M2000_W20_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-51.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M2000_W200_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-58.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M2000_W600_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-04.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M3000_W30_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-08.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M3000_W300_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-13.txt:treeMaker/tree"
    #- "sourceFiles/ZprimeToTT_M3000_W900_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-21.txt:treeMaker/tree"
printEvery: 1000
cpuFrac: 0.99
outputDirBase: "training_results/classifier_trees"
condordir: "training_results/condor_jobs/treemaker"
condorconfig: "configs/condor/condor_config_template_general.submit"
condorscript: "scripts/condor/condor_script_template_general.sh"
outputTag: ""
