categories:
    0:
        name: "lepTop"
        cut: "([jet]_pT_reco > 200) & (abs([jet]_eta_reco) < 2.4) & ([jet]_nConsti_reco >= 3) & ([jet]_nearestGenTopDR_reco < 1) & ([jet]_nearestGenTopIsLeptonic_reco > 0.5)"
        ########## fileName:tree:weight:njetmax ##########
        samples:
            - "sourceFiles/ZprimeToTT_M1000_W10_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-01.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1000_W100_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-08.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1000_W300_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-13.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1250_W12p5_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-18.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1250_W125_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-26.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1250_W375_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-31.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1500_W15_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-36.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1500_W150_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-40.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1500_W450_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-46.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M2000_W20_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-51.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M2000_W200_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-58.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M2000_W600_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-04.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M3000_W30_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-08.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M3000_W300_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-13.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M3000_W900_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-21.txt:treeMaker/tree:1:1000"
    1:
        name: "hadTop"
        cut: "([jet]_pT_reco > 200) & (abs([jet]_eta_reco) < 2.4) & ([jet]_nConsti_reco >= 3) & ([jet]_nearestGenTopDR_reco < 1) & ([jet]_nearestGenTopIsLeptonic_reco < 0.5)"
        samples:
            - "sourceFiles/ZprimeToTT_M1000_W10_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-01.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1000_W100_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-08.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1000_W300_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-13.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1250_W12p5_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-18.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1250_W125_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-26.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1250_W375_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-31.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1500_W15_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-36.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1500_W150_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-40.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M1500_W450_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-46.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M2000_W20_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-51.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M2000_W200_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-56-58.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M2000_W600_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-04.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M3000_W30_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-08.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M3000_W300_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-13.txt:treeMaker/tree:1:1000"
            - "sourceFiles/ZprimeToTT_M3000_W900_TuneCP2_PSweights_13TeV-madgraphMLM-pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-57-21.txt:treeMaker/tree:1:1000"
    2:
        name: "QCD"
        cut: "([jet]_pT_reco > 200) & (abs([jet]_eta_reco) < 2.4) & ([jet]_nConsti_reco >= 3) & ([jet]_nearestGenTopDR_reco > 1)"
        samples:
            - "sourceFiles/QCD_Pt_170to300_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-54-05.txt:treeMaker/tree:1:1000"
            - "sourceFiles/QCD_Pt_300to470_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-54-11.txt:treeMaker/tree:1:1000"
            - "sourceFiles/QCD_Pt_470to600_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM_2021-07-22_15-54-16.txt:treeMaker/tree:1:1000"
            - "sourceFiles/QCD_Pt_600to800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-54-25.txt:treeMaker/tree:1:1000"
            - "sourceFiles/QCD_Pt_800to1000_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM_2021-07-22_15-54-32.txt:treeMaker/tree:1:1000"
            - "sourceFiles/QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15-v1_MINIAODSIM_2021-07-22_15-54-41.txt:treeMaker/tree:1:1000"
            - "sourceFiles/QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM_2021-07-22_15-54-51.txt:treeMaker/tree:1:1000"
            - "sourceFiles/QCD_Pt_1800to2400_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM_2021-07-22_15-55-00.txt:treeMaker/tree:1:1000"
            - "sourceFiles/QCD_Pt_2400to3200_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-PREMIX_RECODEBUG_102X_upgrade2018_realistic_v15_ext1-v1_MINIAODSIM_2021-07-22_15-55-32.txt:treeMaker/tree:1:1000"
xVar: 
    branch: "[jet]_consti_LBGS_x_reco"
    min: -1.0
    max: 1.0
    nBin: 50
yVar: 
    branch: "[jet]_consti_LBGS_y_reco"
    min: -1.0
    max: 1.0
    nBin: 50
constiBranch: "[jet]_nConsti_reco"
layers:
    ########## Energy fraction layers ##########
    - valueBranch: "[jet]_consti_enFrac_reco"
      cutBranch: "abs([jet]_consti_id_reco) == 11"
      resolverOperation: "{newValue}+{oldValue}"
    - valueBranch: "[jet]_consti_enFrac_reco"
      cutBranch: "abs([jet]_consti_id_reco) == 13"
      resolverOperation: "{newValue}+{oldValue}"
    - valueBranch: "[jet]_consti_enFrac_reco"
      cutBranch: "abs([jet]_consti_id_reco) == 22"
      resolverOperation: "{newValue}+{oldValue}"
    - valueBranch: "[jet]_consti_enFrac_reco"
      cutBranch: "abs([jet]_consti_id_reco) == 130"
      resolverOperation: "{newValue}+{oldValue}"
    - valueBranch: "[jet]_consti_enFrac_reco"
      cutBranch: "abs([jet]_consti_id_reco) == 211"
      resolverOperation: "{newValue}+{oldValue}"
    ########## Secondary vertex layers ##########
    - valueBranch: "1.0 - (min(3, [jet]_consti_svdxy_reco)/3.0)"
      cutBranch: "([jet]_consti_svdxy_reco > 0) * ([jet]_consti_pT_reco > 20) * (abs([jet]_consti_id_reco) == 11)"
      resolverOperation: "{newValue} if ({newResolver} > {oldResolver}) else {oldValue}"
      resolverUpdate: "max({newResolver}, {oldResolver})"
      resolverBranch: "[jet]_consti_pT_reco"
    - valueBranch: "1.0 - (min(3, [jet]_consti_svdxy_reco)/3.0)"
      cutBranch: "([jet]_consti_svdxy_reco > 0) * ([jet]_consti_pT_reco > 20) * (abs([jet]_consti_id_reco) == 13)"
      resolverOperation: "{newValue} if ({newResolver} > {oldResolver}) else {oldValue}"
      resolverUpdate: "max({newResolver}, {oldResolver})"
      resolverBranch: "[jet]_consti_pT_reco"
    - valueBranch: "1.0 - (min(3, [jet]_consti_svdxy_reco)/3.0)"
      cutBranch: "([jet]_consti_svdxy_reco > 0) * ([jet]_consti_pT_reco > 20) * (abs([jet]_consti_id_reco) == 211)"
      resolverOperation: "{newValue} if ({newResolver} > {oldResolver}) else {oldValue}"
      resolverUpdate: "max({newResolver}, {oldResolver})"
      resolverBranch: "[jet]_consti_pT_reco"
jetName : "[jet]:jet_selectedPatJetsAK15PFPuppi_boost_2_1_sd_0p1_0_1"
network: CNN2
testFraction: 0.2
batchSize: 1000
loadEventPerJob: 500
cpuFrac: 0.99
